### ISSUE TITLE
Custom renderer issue

### ISSUE THREAD

**Issue by NihalNadaf-UI** [eclipsesource/jsonforms-react-seed#100]
Issue:- When we are creating custom renderers, jsonforms internally binds custom renderer with uischema.json (scope) and data.json (field name) 

Expectation:- Instead of binding both data.json and uischema.json can we only bind our renderer to uischema.json

**Comment by sdirix** [comment]
I'm not sure about the use case you are trying to solve. If you have any JSON Forms questions please ask them in the [community forum](https://jsonforms.discourse.group/).
