### ISSUE TITLE
Issue build error

### ISSUE THREAD

**Issue by lalita98** [eclipsesource/jsonforms-react-seed#103]
When running this command , an error occurred
..\jsonforms\jsonforms-editor>npm run build

> build
> lerna run build

lerna notice cli v4.0.0
lerna info Executing command in 2 packages: "npm run build"
lerna ERR! npm run build exited 1 in '@jsonforms/editor'
lerna ERR! npm run build stdout:

> @jsonforms/editor@0.1.0 build ..\jsonforms\jsonforms-editor\jsonforms-editor
> rimraf dist && rollup --config rollup.config.ts

lerna ERR! npm run build stderr:
'rollup' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.22621
npm ERR! argv "..\\nodejs\\node.exe" "..\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v18.14.2
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! @jsonforms/editor@0.1.0 build: `rimraf dist && rollup --config rollup.config.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @jsonforms/editor@0.1.0 build script 'rimraf dist && rollup --config rollup.config.ts'.
npm ERR! This is most likely a problem with the @jsonforms/editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && rollup --config rollup.config.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @jsonforms/editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls @jsonforms/editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ..\jsonforms\jsonforms-editor\jsonforms-editor\npm-debug.log
lerna ERR! npm run build exited 1 in '@jsonforms/editor'
[npm-debug.log](https://github.com/eclipsesource/jsonforms-react-seed/files/10937361/npm-debug.log)

**Comment by sdirix** [comment]
This is the wrong repository. If you have issues with the `@jsonforms/editor` please report them in https://github.com/eclipsesource/jsonforms-editor
