### ISSUE TITLE
array no default rendering 

### ISSUE THREAD

**Issue by ldelaprade** [eclipsesource/jsonforms-react-seed#105]
when json schema contains:
            "properties": {
              "labels": {
                "type": "array",
                "items": [{ "type": "string" }]
              },
where, for example, matching data could be:
            {
                "labels"     : ["257","340"],
            },
Then, for this array,  default renderer displays:
"No applicable renderer found."

**Comment by sdirix** [comment]
Hi @ldelaprade,

At the moment we only support array item objects, not array item arrays. If you need support for this you need to implement a custom renderer.
