### ISSUE TITLE
How to get the Field name from jsonschema

### ISSUE THREAD

**Issue by KIC** [eclipsesource/jsonforms-react-seed#110]
In the Rating example the label "Rating" is hard coded:
https://github.com/eclipsesource/jsonforms-react-seed/blob/3ed669c5e6434919b090c7c9981f3c9a643c125c/src/Rating.tsx#L16C1-L17C1

How would I get the label from the jsonschema?

**Comment by sdirix** [comment]
Please use the [JSON Forms community](https://jsonforms.discourse.group/) for questions.

You get a lot of properties injected, including a pre-calculated `label` in the props which can just be used.
