### ISSUE TITLE
upgrade to Material UI v5

### ISSUE THREAD

**Issue by yellowbean** [eclipsesource/jsonforms-react-seed#111]
current version only user material v4

**Comment by sdirix** [comment]
Hi @yellowbean, we are using Material v5, see [here](https://github.com/eclipsesource/jsonforms-react-seed/blob/3ed669c5e6434919b090c7c9981f3c9a643c125c/package.json#L11-L15). I'll therefore close this issue. Feel free to comment or reopen if something is unclear.
