### ISSUE TITLE
Clone not working

### ISSUE THREAD

**Issue by SanderKok01** [eclipsesource/jsonforms-react-seed#121]
After cloning the repository, I got a blank page. It appear that since `src/index.tsx` is missing, the page does not load.
Also, it renders the `index.html` from the root folder instead of the one in `public/index.html`.

What to do now?

**Comment by lucas-koehler** [comment]
Hi @SanderKok01 , thanks for raising this. We recently moved from Create React App to ViteJS in #120 . During this refactoring we missed adapting the README to tell you to run `npm run build` before `npm start`. I opened PR #122  to fix the README and remove the obsolete index.html in the public folder.
