### ISSUE TITLE
Cannot launch the app

### ISSUE THREAD

**Issue by shinout** [eclipsesource/jsonforms-react-seed#17]
Hi, I installed this package to fail to launch the app.
It says the following error.

```
./node_modules/@material-ui/lab/Slider/Slider.js
Module not found: Can't resolve '@babel/runtime/helpers/builtin/classCallCheck' in '/path/to/jsonforms-react-seed/node_modules/@material-ui/lab/Slider'
```

MacOS X 10.12.6
Node.js v8.9.0
npm 5.5.1

**Comment by shinout** [comment]
It occurs because `material-ui` uses fixed version of `@babel 7.0.0-beta.42`.
Setting `"@babel/runtime": "7.0.0-beta.42"` in the `package.json` worked.

**Comment by edgarmueller** [comment]
Thanks for the report! We'll try to reproduce this error and see if we can come up with a fix.

**Comment by sdirix** [comment]
Please reopen if this is not fixed for you
