### ISSUE TITLE
render image?

### ISSUE THREAD

**Issue by kiahmed** [eclipsesource/jsonforms-react-seed#20]
hi, how can I use it to display image with custom height/width and border or change the location of the form or entire object or am I asking too much ?

**Comment by sdirix** [comment]
This is probably too late but you could use a custom control and check this question on Spectrum: https://spectrum.chat/jsonforms/general/adding-an-image-to-a-form~f159b04e-3786-480e-8a6f-160092816d12

Please let me know if you have further issues
