### ISSUE TITLE
scheme based condition are not working with 2.0.7

### ISSUE THREAD

**Issue by pragnesh-is** [eclipsesource/jsonforms-react-seed#24]
Also, there is no examples and documents how to use schema based conditions, please can you provide how to use it with master branch code of this repo.

**Comment by edgarmueller** [comment]
The idea of schema based conditions is that you can provide a schema which the data referenced via the `scope` property will be validated against, i.e. if validation succeeds the `effect` will be triggered. So if you want to trigger formulate a condition which checks against a array, all you need to do is to specify the respective schema, e.g. if you want an effect to be triggered whenever an array has at least three items, the condition would look like:

```js
condition: {
  scope: '#/properties/foo',
  schema: {
    minItems: 3
  }
}
```

I hope this answers your question, if not, please re-open.
