### ISSUE TITLE
Vanilla renderer, array example not showing delete buttons. 

### ISSUE THREAD

**Issue by jakobgn** [eclipsesource/jsonforms-react-seed#36]
Steps to reproduce:
1) clone master (version 2.2.2)
2) install vanilla renderer instead of material and adjust index.ts
3) copy schema/ui-schema/data from https://jsonforms.io/examples/array
4) start
Result: no delete buttons for array like in the material version 

![image](https://user-images.githubusercontent.com/29198565/56141018-46ddf900-5f9c-11e9-839e-3eca1166e920.png)

**Comment by edgarmueller** [comment]
Thanks for the report! Yes, unfortunately, the vanilla renderer lacks some of the features, as we are mostly focused on the material renderers. If this feature is crucial for you, we can try to address it soon in of the upcoming releases (but PRs are of course also always welcome 😃 )

**Comment by jakobgn** [comment]
We (big corp) are considering to use this library, but not with material, and it would be nice for demo purposes if it was fixed as soon as possible, to show that it is a valid solution :)

**Comment by edgarmueller** [comment]
I see, we'll try to address this issue soon then: I've created https://github.com/eclipsesource/jsonforms/issues/1348 for that.

**Comment by jakobgn** [comment]
thanks!

**Comment by edgarmueller** [comment]
Fixed and released via 2.2.3. If there anythings else, let us know.
