### ISSUE TITLE
Update Seed Repo to work with new version 2.3.0.

### ISSUE THREAD

**Issue by shivgarg5676** [eclipsesource/jsonforms-react-seed#40]
2.3.0 is going to be a breaking change. We need to update seed repo to accommodate such change.

**Comment by edgarmueller** [comment]
Yes, thanks for the report. I've prepared something on my personal branch https://github.com/edgarmueller/jsonforms-react-seed/tree/isolated-forms, but we'll update upstream once 2.3.0 final is availab.e
