### ISSUE TITLE
App not working out of the box.

### ISSUE THREAD

**Issue by shivgarg5676** [eclipsesource/jsonforms-react-seed#46]
If you try to launch seed app on code sandbox it compiles with errors. 
https://codesandbox.io/embed/github/eclipsesource/jsonforms-react-seed/tree/master/
https://codesandbox.io/s/github/eclipsesource/jsonforms-react-seed/tree/master/

Will need to fix issues in master so that it compiles correctly out of the box.

**Comment by abraham** [comment]
It worked locally for me. There might be a dependency that codesandbox doesn't support.

**Comment by sdirix** [comment]
@shivgarg5676 we updated all dependencies, maybe you want to try it again

**Comment by shivgarg5676** [comment]
@sdirix  Yes it is working now. Tested today only. 
https://codesandbox.io/s/github/eclipsesource/jsonforms-react-seed
