### ISSUE TITLE
Horizontal scrollbar should not appear

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms-react-seed#59]
Investigate why horizontal scrollbar appears and potentially fix.

**Comment by TheZoker** [comment]
This 125% width creates the overflow:
![image](https://user-images.githubusercontent.com/1368405/85791552-4ad5e100-b732-11ea-8d91-967575bf2ac9.png)

(Unfortunately the ubuntu screenshot tool did not let me take a screenshot when inspecting the element, then the overflow would be visible).

This change was introduces here:
https://github.com/eclipsesource/jsonforms/pull/1585/files#diff-680298bbf86fe5fdc48353b7c16321a0R52

**Comment by TheZoker** [comment]
I guess this issue can be closed, since this PR got merged a while ago:
https://github.com/eclipsesource/jsonforms/pull/1629
