### ISSUE TITLE
Type null or string for date value

### ISSUE THREAD

**Issue by massimomannoni** [eclipsesource/jsonforms-react-seed#61]
Hi , starting from "seed" https://jsonforms.io/docs/getting-started , change the json schema
"due_date": { "type": "string", "type": ["string", "null"], "format": "date" },
adding "null" to the types array.
As result, the icon used to display calendar popup, disappear.
Thanks in advance
MM

**Comment by sdirix** [comment]
We register our `date`, `date-time` and `time` renderers only for `type: "string"` elements. If you want to also use them for `type: ["string", "null"]` you need to register them also for this type combination.

**Comment by sdirix** [comment]
I'll close this ticket for now. If you have further questions feel free to ask them on our [community platform](https://spectrum.chat/jsonforms).
