### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by dpatra** [eclipsesource/jsonforms-react-seed#70]
jsonforms.io is down at the moment. Cam some one look that up.

**Comment by sdirix** [comment]
We host our Website via Netlify and it seems to be down at the moment, see https://www.netlifystatus.com/

However it looks like you can still access this preview version of the next Website iteration: https://deploy-preview-165--jsonforms.netlify.app/

**Comment by sdirix** [comment]
Website is available again
