### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by smshuja** [eclipsesource/jsonforms-react-seed#71]
Hello,

Trying to get this to work with one of our json-schemas. Its a valid schema and works fine in vscode with autocomplete, validation etc.

Here is the codesandbox example based on this repo.

https://codesandbox.io/s/optimistic-turing-hjo1w?file=/src/App.tsx

**Comment by sdirix** [comment]
Hi @smshuja, thanks for the report. On a first glance it looks like that our resolving code can't handle the structure of the JSON Schema, ending up in an endless loop. Can you try to create a minimal example in which this problem occurs and report an issue against our [main JSON Forms repository](https://github.com/eclipsesource/jsonforms)?

**Comment by sdirix** [comment]
Closing this for now. Please reopen if still relevant for you.
